# Generated by Django 3.2.25 on 2024-07-25 17:40

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import profiles.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('age', models.IntegerField(validators=[profiles.models.age])),
                ('phone_number', models.CharField(max_length=11, validators=[profiles.models.phone])),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator(message='Please enter a valid email address.')])),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Transgender', 'Transgender'), ('Prefer not to say', 'Prefer not to say')], default='Prefer not to say', max_length=20)),
                ('profile_image', models.ImageField(default='images/default_profile_tpcl4s', upload_to='images/')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
